"""Phase 08.5 async DummyAdapter for testing and local dry-runs."""

from __future__ import annotations

from pathlib import Path

from forge_os.adapters.async_base import (
    AsyncAgentHandle,
    AsyncBaseKernelAdapter,
    ToolList,
)
from forge_os.agents.models import AgentDefinition, OutputArtifact


class AsyncDummyAdapter(AsyncBaseKernelAdapter):
    """Async deterministic no-network adapter that synthesizes expected artifacts."""

    adapter_id = "async-dummy"
    optional_capabilities = frozenset({"stop_agent", "get_status"})

    def __init__(self, project_root: Path | None = None, *, create_outputs: bool = True) -> None:
        self.project_root = project_root
        self.create_outputs = create_outputs

    async def get_default_tools(self) -> ToolList:
        return ["read_file", "write_file", "list_files"]

    async def spawn_agent(
        self,
        persona: AgentDefinition,
        context: str,
        tools: ToolList,
    ) -> AsyncAgentHandle:
        """Return a completed handle and optionally write deterministic outputs."""

        granted_tools = await self._intersect_tools(tools)
        outputs = await self._write_outputs(persona) if self.create_outputs else []
        return AsyncAgentHandle(
            provider=self.adapter_id,
            persona_id=persona.id,
            stage_id=persona.stage_ids[0] if persona.stage_ids else None,
            status="completed",
            outputs=outputs,
            metadata={
                "context_length": len(context),
                "tools": granted_tools,
                "deterministic": True,
            },
        )

    async def _write_outputs(self, persona: AgentDefinition) -> list[OutputArtifact]:
        if self.project_root is None:
            return []

        outputs: list[OutputArtifact] = []
        for stage_id in persona.stage_ids[:1]:
            relative_path = self._default_output_path(stage_id)
            artifact_path = self.project_root / relative_path
            artifact_path.parent.mkdir(parents=True, exist_ok=True)
            if not artifact_path.exists():
                artifact_path.write_text(
                    self._artifact_content(persona, stage_id),
                    encoding="utf-8",
                )
            outputs.append(
                OutputArtifact(
                    path=relative_path,
                    kind="file",
                    description=f"Deterministic async dummy output for {persona.name}",
                )
            )
        return outputs

    @staticmethod
    def _default_output_path(stage_id: str) -> str:
        if stage_id == "srs":
            return "SRS.md"
        return f"pipeline/log/{stage_id}-agent-output.md"

    @staticmethod
    def _artifact_content(persona: AgentDefinition, stage_id: str) -> str:
        return (
            f"# {persona.name} Output\n\n"
            f"Stage: `{stage_id}`\n\n"
            "This deterministic artifact was generated by `AsyncDummyAdapter` for testing.\n"
        )
